name: search_map_place_v2_example
description: Examples for the search_map_place_v2 package
homepage: https://github.com/rubensdemelo/search_map_place_v2

environment:
  sdk: ">=2.10.0-38.0.dev <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  search_map_place_v2:
    path: ../
  flutter_polyline_points:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
